### ISSUE TITLE
Implement Marina plugin to enable the app to connect user's wallet

### ISSUE THREAD

**Issue by liquidao-dev** [liquiDAO/app#5]
## Overview

The users of [Marina browser extension ](https://chrome.google.com/webstore/detail/marina/nhanebedohgejbllffboeipobccgedhl) need to be able to connect their Liquid wallet to the LiquiDAO app. This will allow to get addresses, compute balances and create transactions using the private keys kept safe in the extension, without the need for the user to copy/paste their private key (mnemonic seed) in a web application, leading to potential loss of funds.

## Requirements

To implements this feature it requires:

- Having `Marina` installed on Chrome or Chromium. Link: https://chrome.google.com/webstore/detail/marina/nhanebedohgejbllffboeipobccgedhl
- Having completed the full-screen on-boarding procedure and having created a wallet with the backup seed saved and written down in a safe place.
- Having read the documentation of Marina API https://docs.vulpem.com/marina/introduction

## Deliverables

1) The app should detect globally that marina is installed. Link: https://docs.vulpem.com/marina/getting-started#browser-detection. If NOT installed the buttons with text `Connect wallet` in `src/components/Menu/Menu.js` and in `src/pages/Swap/Swap.tsx` needs to have the text `Install Marina wallet` and have a link to open in a new tab the following link: https://vulpem.com/marina.
2) If the extension is installed and detected, check if the current website has been enabled already (ie. connected) calling the async `marina.isEnabled` API injected in the `window` DOM. **If yes skip to the 5th step directly**
3) If the extension is installed and detected but NOT enabled the current website, the two buttons with text `Connect wallet` needs to have an onClick prop that triggers the async `marina.enable` API injected in the `window` DOM. Link https://docs.vulpem.com/marina/connect#enable
4) a window pop-up should appear and the user must ACCEPT. the button text and component react state `isConnected` needs to change via `setIsConnected`.
5) this new `isConnected` state must hide the `Connect wallet` entirely in the `Menu.js` and replacing the text of the one in `Swap.tsx` with `Swap` instead of `Connect wallet`.

**Comment by KOSIDOCS** [comment]
Hi, I can't find the marina.isEnabled API. It's not also on the documentation.
